version: "3.8" # 사용하는 Docker Compose 버전에 맞게 설정

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    image: ghcr.io/devheun/hearlers:latest
    platform: linux/amd64
