services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - JWT_SECRET=gcgjkaq/wyC+4j2JyUZpjBdMerxiOQ61GAXSz/RXwq4=
      - KAKAO_CLIENT_ID=ac5e6b86f2486a704110274834a596d5