version: "3.8" # 사용하는 Docker Compose 버전에 맞게 설정

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JWT_SECRET: ${JWT_SECRET}
        KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
